version: '3'
services:
  scheduled:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: local-db-test
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: scheduled
      TZ: Asia/Seoul
    volumes:
      - ./data/mysql/:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

